### ISSUE TITLE
Change logic behind "socks" category to match "other" and "facial hair"

### ISSUE THREAD

**Issue by redgouf** [MCBTay/XLGearModifier#181]
I never made a socks item for this category, so I never tested it. Mark Murderous found out they will replace the shoes currently.

**Comment by MCBTay** [comment]
Right, I was thinking this was exactly what we'd want to do.  No problem.

**Comment by redgouf** [comment]
This is now working on latest main.

![Image](https://user-images.githubusercontent.com/13354972/176242622-386e4876-7e70-42c3-a7f1-2030133bb04d.png)
![Image](https://user-images.githubusercontent.com/13354972/176242623-7f166e11-04d5-40a7-a47f-56e16e14f4ae.png)
